## 00. PyTorch Fundamentals

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.1+cu118


## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using Torch.tensor()

In [9]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [12]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [16]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX[1]

tensor([ 9, 10])

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                       [[10,11,12],[13,14,15],[16,17,18]]
                      ])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
TENSOR[0][1]

tensor([4, 5, 6])

In [27]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors
Why Random Tensors?
Random tensors are important as neural networks learn  by starting with tensors full of random numbers and then adjust those random number to better represent the data.

`Start with random numbers -> Look at data -> Update Random Numbers -> Look at data -> Update Random Numbers`

In [29]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2990, 0.1884, 0.9025, 0.1092],
        [0.1216, 0.4438, 0.0310, 0.4830],
        [0.6931, 0.7517, 0.1674, 0.7736]])

In [30]:
random_tensor.ndim

2

In [31]:
random_tensor.shape

torch.Size([3, 4])

In [35]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [36]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

### Range of tensors and tensors-like

In [44]:
# Creating a range of tensors
range_of_tensors_with_step = torch.arange(start=0,end=1000,step=99)
range_of_tensors_with_step

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [46]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = range_of_tensors_with_step)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors we run into in Pytorch and deep learning.

Others are tensor not in right shape, and tensor not on right device.

In [47]:
float_32_tensor = torch.tensor([3.0,4.5,5.0], 
                               dtype = None, 
                               device = None, 
                               requires_grad = False)
float_32_tensor

tensor([3.0000, 4.5000, 5.0000])

In [48]:
float_32_tensor.dtype

torch.float32

In [58]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [59]:
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [61]:
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.9009, 0.9050, 0.3982, 0.7461],
        [0.6895, 0.6288, 0.7548, 0.6423],
        [0.4109, 0.9815, 0.4476, 0.9668]])

In [68]:
# Find out details of the tensor
print(rand_tensor)
print(f"Datatype: {rand_tensor.dtype}")
print(f"Shape(its an attribute): {rand_tensor.shape}")
print(f"Size(its a function): {rand_tensor.size()}")
print(f"Device: {rand_tensor.device}")

tensor([[0.9009, 0.9050, 0.3982, 0.7461],
        [0.6895, 0.6288, 0.7548, 0.6423],
        [0.4109, 0.9815, 0.4476, 0.9668]])
Datatype: torch.float32
Shape(its an attribute): torch.Size([3, 4])
Size(its a function): torch.Size([3, 4])
Device: cpu


### Manipulating tensors (tensor operations)

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [70]:
# Addition torch.add(tensor,1)
tensor = torch.tensor([1,2,3])
tensor+1

tensor([2, 3, 4])

In [71]:
# Multiplication torch.mul(tensor,10)
tensor*10

tensor([10, 20, 30])

In [72]:
# Subtracton torch.subtract(tensor,1)
tensor-1

tensor([0, 1, 2])

In [73]:
tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [80]:
# Matrix Multiplication
torch.matmul(tensor,tensor) #can use mm() instead of matmul() or use @ inbetween two tensors

tensor(14)

In [81]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

This does not work as inner dimension does not match, while in the one below the inner dimension matches

In [82]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.1461, 0.0859, 0.2431],
        [0.0464, 0.0244, 0.0929],
        [0.4942, 0.2838, 0.8588]])

To fix our tensor shape issues, we can manipulate the shape of our tensors using a transpose.

A **transpose** switches the axes or dimensions of a given vector

We can transpose a tensor using the attribute **T**

In [83]:
torch.matmul(torch.rand(3,2),torch.rand(3,2).T)

tensor([[0.6009, 0.3209, 0.5092],
        [0.6706, 0.1996, 0.2707],
        [0.9227, 0.5547, 0.8981]])

In [89]:
tensorA = torch.Tensor([[1,2,3],
                      [4,5,6]])
tensorB = torch.Tensor([[9,8,7],
                        [6,5,4]])
print(f"Tensor A shape: {tensorA.shape}\nTensor B shape: {tensorB.shape}")
print(f"Multiplying Tensor A having shape {tensorA.shape} with Tensor B.T having shape {tensorB.T.shape}")
print(f"Output: {tensorA@tensorB.T}")

Tensor A shape: torch.Size([2, 3])
Tensor B shape: torch.Size([2, 3])
Multiplying Tensor A having shape torch.Size([2, 3]) with Tensor B.T having shape torch.Size([3, 2])
Output: tensor([[ 46.,  28.],
        [118.,  73.]])
