## 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.1+cu118


## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using Torch.tensor()

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                       [[10,11,12],[13,14,15],[16,17,18]]
                      ])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
TENSOR[0][1]

tensor([4, 5, 6])

In [16]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors
Why Random Tensors?
Random tensors are important as neural networks learn  by starting with tensors full of random numbers and then adjust those random number to better represent the data.

`Start with random numbers -> Look at data -> Update Random Numbers -> Look at data -> Update Random Numbers`

In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2254, 0.5425, 0.4372, 0.0987],
        [0.4276, 0.0253, 0.4210, 0.6328],
        [0.2274, 0.4185, 0.1741, 0.6469]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Range of tensors and tensors-like

In [24]:
# Creating a range of tensors
range_of_tensors_with_step = torch.arange(start=0,end=1000,step=99)
range_of_tensors_with_step

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = range_of_tensors_with_step)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors we run into in Pytorch and deep learning.

Others are tensor not in right shape, and tensor not on right device.

In [26]:
float_32_tensor = torch.tensor([3.0,4.5,5.0], 
                               dtype = None, 
                               device = None, 
                               requires_grad = False)
float_32_tensor

tensor([3.0000, 4.5000, 5.0000])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [29]:
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [30]:
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.0907, 0.7706, 0.7351, 0.9561],
        [0.2945, 0.2676, 0.9742, 0.5692],
        [0.4507, 0.9972, 0.8458, 0.9423]])

In [31]:
# Find out details of the tensor
print(rand_tensor)
print(f"Datatype: {rand_tensor.dtype}")
print(f"Shape(its an attribute): {rand_tensor.shape}")
print(f"Size(its a function): {rand_tensor.size()}")
print(f"Device: {rand_tensor.device}")

tensor([[0.0907, 0.7706, 0.7351, 0.9561],
        [0.2945, 0.2676, 0.9742, 0.5692],
        [0.4507, 0.9972, 0.8458, 0.9423]])
Datatype: torch.float32
Shape(its an attribute): torch.Size([3, 4])
Size(its a function): torch.Size([3, 4])
Device: cpu


### Manipulating tensors (tensor operations)

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [32]:
# Addition torch.add(tensor,1)
tensor = torch.tensor([1,2,3])
tensor+1

tensor([2, 3, 4])

In [33]:
# Multiplication torch.mul(tensor,10)
tensor*10

tensor([10, 20, 30])

In [34]:
# Subtracton torch.subtract(tensor,1)
tensor-1

tensor([0, 1, 2])

In [35]:
tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [36]:
# Matrix Multiplication
torch.matmul(tensor,tensor) #can use mm() instead of matmul() or use @ inbetween two tensors

tensor(14)

In [37]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

This does not work as inner dimension does not match, while in the one below the inner dimension matches

In [38]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.3213, 0.5633, 0.6699],
        [0.3097, 0.5508, 0.6257],
        [0.4374, 0.7931, 0.8462]])

To fix our tensor shape issues, we can manipulate the shape of our tensors using a transpose.

A **transpose** switches the axes or dimensions of a given vector

We can transpose a tensor using the attribute **T**

In [39]:
torch.matmul(torch.rand(3,2),torch.rand(3,2).T)

tensor([[0.4389, 0.6407, 0.3066],
        [0.8637, 1.2803, 0.6203],
        [0.0923, 0.1693, 0.0948]])

In [40]:
tensorA = torch.Tensor([[1,2,3],
                      [4,5,6]])
tensorB = torch.Tensor([[9,8,7],
                        [6,5,4]])
print(f"Tensor A shape: {tensorA.shape}\nTensor B shape: {tensorB.shape}")
print(f"Multiplying Tensor A having shape {tensorA.shape} with Tensor B.T having shape {tensorB.T.shape}")
print(f"Output: {tensorA@tensorB.T}")

Tensor A shape: torch.Size([2, 3])
Tensor B shape: torch.Size([2, 3])
Multiplying Tensor A having shape torch.Size([2, 3]) with Tensor B.T having shape torch.Size([3, 2])
Output: tensor([[ 46.,  28.],
        [118.,  73.]])


### Tensor Aggregation (Min, Max, Mean, Sum)

In [41]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [43]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [44]:
# Find the mean - torch.mean requires tensor type to be float or complex
torch.mean(x.type(torch.float16)), x.type(torch.float16).mean()

(tensor(45., dtype=torch.float16), tensor(45., dtype=torch.float16))

In [45]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [46]:
# Find the index where minimum value occurs using argmin()
x.argmin(), x[x.argmin()]

(tensor(0), tensor(0))

In [47]:
# Find the index where minimum value occurs using argmax()
x.argmax(), x[x.argmax()]

(tensor(9), tensor(90))

### Reshaping, stacking, squeezing, unsqueezing and permuting tensors

In [48]:
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [49]:
# Reshape to (2,5)
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [50]:
# chage the view (a view of a tensor shares the same memory as the original tensor)
z = x.view(1,10)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [51]:
z[:,0] = 11
z, x

(tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [52]:
# stack tensors on top of each other
x_stacked_vertically = torch.stack([x,x,x,x], dim = 0) # stack has dimension 0 by default
x_stacked_vertically, x_stacked_vertically.shape # can use vstack instead, it has dim =0 by default

(tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [53]:
x_stacked_horizontally = torch.stack([x,x,x,x], dim = 1)
x_stacked_horizontally, x_stacked_horizontally.shape  # can use hstack instead, it has dim = 1 by default

(tensor([[11., 11., 11., 11.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]),
 torch.Size([10, 4]))

In [54]:
# torch.squeeze() removes all single dimensions from a target tensor
x = torch.rand(1,9)
x, x.shape

(tensor([[0.7368, 0.8329, 0.0101, 0.8771, 0.3135, 0.9095, 0.6130, 0.5292, 0.4004]]),
 torch.Size([1, 9]))

In [55]:
x_squeezed = x.squeeze()
x_squeezed, x_squeezed.shape

(tensor([0.7368, 0.8329, 0.0101, 0.8771, 0.3135, 0.9095, 0.6130, 0.5292, 0.4004]),
 torch.Size([9]))

In [56]:
# torch.unsqueeze()- adds a single dimension to a target tensor at a specific dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[0.7368, 0.8329, 0.0101, 0.8771, 0.3135, 0.9095, 0.6130, 0.5292, 0.4004]]),
 torch.Size([1, 9]))

In [57]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[0.7368],
         [0.8329],
         [0.0101],
         [0.8771],
         [0.3135],
         [0.9095],
         [0.6130],
         [0.5292],
         [0.4004]]),
 torch.Size([9, 1]))

In [58]:
# torch.permute() - returns a view and rearanges the dimensions of the target tensor.
x_orig = torch.rand(size = (224,224,3))
x_permuted = x_orig.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"previous shape: {x_orig.shape}")
print(f"new shape: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


### Indexing(selecting data from tensors)

In [60]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [61]:
# Indexing on this new tensor x
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [63]:
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [64]:
# You can use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [66]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [67]:
# Get all values of 0th but only the index 1 of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [68]:
# Getindex 0 of 0th and 1st dimension and all  values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [69]:
# Index on x to return 9
x[0][2][2], x[0,2,2]

(tensor(9), tensor(9))

In [70]:
# Index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## Pytorch tensors and numpy

Pytorch has to interact with Numpy and viceversa

* Data in Numpy, want in PyTorch Tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy ->torch.Tensor.numpy()

In [76]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning from converting from numpy to tensor dtype is float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.nu