## 00. PyTorch Fundamentals

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.1+cu118


## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using Torch.tensor()

In [9]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [12]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [16]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX[1]

tensor([ 9, 10])

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                       [[10,11,12],[13,14,15],[16,17,18]]
                      ])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
TENSOR[0][1]

tensor([4, 5, 6])

In [27]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors
Why Random Tensors?
Random tensors are important as neural networks learn  by starting with tensors full of random numbers and then adjust those random number to better represent the data.

`Start with random numbers -> Look at data -> Update Random Numbers -> Look at data -> Update Random Numbers`

In [29]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2990, 0.1884, 0.9025, 0.1092],
        [0.1216, 0.4438, 0.0310, 0.4830],
        [0.6931, 0.7517, 0.1674, 0.7736]])

In [30]:
random_tensor.ndim

2

In [31]:
random_tensor.shape

torch.Size([3, 4])

In [35]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [36]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

### Range of tensors and tensors-like

In [44]:
# Creating a range of tensors
range_of_tensors_with_step = torch.arange(start=0,end=1000,step=99)
range_of_tensors_with_step

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [46]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = range_of_tensors_with_step)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors we run into in Pytorch and deep learning.

Others are tensor not in right shape, and tensor not on right device.

In [47]:
float_32_tensor = torch.tensor([3.0,4.5,5.0], 
                               dtype = None, 
                               device = None, 
                               requires_grad = False)
float_32_tensor

tensor([3.0000, 4.5000, 5.0000])

In [48]:
float_32_tensor.dtype

torch.float32

In [53]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [54]:
float_16_tensor.dtype

torch.float16