## 00. PyTorch Fundamentals

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.1+cu118


## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using Torch.tensor()

In [9]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [12]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [16]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX[1]

tensor([ 9, 10])

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                       [[10,11,12],[13,14,15],[16,17,18]]
                      ])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
TENSOR[0][1]

tensor([4, 5, 6])

In [27]:
TENSOR.shape

torch.Size([2, 3, 3])